### ISSUE TITLE
NullPointerException on getProviderName() when a valid provider exists

### ISSUE THREAD

**Issue by manmedia** [JavaMoney/jsr354-ri#242] opened 2018-11-07 23:05 UTC
The following code generates a query successfully

`CurrencyQuery query = CurrencyQueryBuilder.of().setProviderName("ProviderClassName").setCurrencyCodes("CNH").build();
`

But when the appropriate CurrencyProvider imp is loaded and getCurrencies(CurrencyQuery) is invoked, the following code results into NPE.

```
if (!query.isEmpty() && query.getProviderName().equals("SomeName")) {

      for (CurrencyUnit c : currencySet) {

          if (c.getCurrencyCodes().equals(query.getCurrencyCodes()) {

             return Collections.singleton(c);

          }

     }

}

```

We are always building the currency query such that it will have a provider name and currency unit. The above code results into an NPE for getProviderName() where a provider name actually exists.

**Comment by keilw** [comment] 2018-11-07 23:32
This looks like a duplicate of https://github.com/JavaMoney/jsr354-api/issues/100.

**Comment by keilw** [comment] 2018-12-31 01:54
Closing here because it was already raised in the API

**Closed by keilw** 2018-12-31 01:54 UTC
Labels: duplicate
