### ISSUE TITLE
Formatting with a custom pattern of the negative amounts incorrectly puts a minus before currency code

### ISSUE THREAD

**Issue by stokito** [JavaMoney/jsr354-ri#282] opened 2019-01-29 13:46 UTC
During fixing #193 I covered with tests almost everything what is involved and I found a critical bug with parsing of negative amounts. See `AmountNumberTokenTest.testWithCustomPatternForNegativeAmount`:

```java
    @Test
    public void testWithCustomPatternForNegativeAmount() {
        Money moneyNegative = Money.of(-12345.23, "EUR");
        testCustomFormat(moneyNegative, "#,##0.## ¤", "-12.345,23 EUR", "-12.345,23 EUR", CODE);
        testCustomFormat(moneyNegative, "#,##0.##¤", "-12.345,23EUR", "-12.345,23EUR", CODE);
//FIXME        testCustomFormat(moneyNegative, "¤ #,##0.##", "EUR -12.345,23", "EUR -12.345,23", CODE);
        testCustomFormat(moneyNegative, "¤#,##0.##", "EUR-12.345,23", "EUR-12.345,23", CODE);
        testCustomFormat(moneyNegative, "LITERAL ¤#,##0.##", "LITERAL EUR-12.345,23", "LITERAL EUR-12.345,23", CODE);
//FIXME        testCustomFormat(moneyNegative, "LITERAL ¤ #,##0.##", "LITERAL EUR -12.345,23", "LITERAL EUR -12.345,23", CODE);
//FIXME        testCustomFormat(moneyNegative, "LITERAL ¤ #,##0.## LITERAL", "LITERAL EUR -12.345,23 LITERAL", "LITERAL EUR -12.345,23 LITERAL", CODE);
//FIXME        testCustomFormat(moneyNegative, "LITERAL #,##0.## ¤ LITERAL", "LITERAL -12.345,23 EUR LITERAL", "LITERAL -12.345,23 EUR LITERAL", CODE);
//FIXME        testCustomFormat(moneyNegative, "LITERAL #,##0.##¤ LITERAL", "LITERAL -12.345,23EUR LITERAL", "LITERAL -12.345,23EUR LITERAL", CODE);
    }
```

All those commented assertions are failed.
I don't have enough of time to fix that but I hope this happens only when you trying to specify a custom pattern which I hope a rarely case

**Comment by keilw** [comment] 2019-01-29 13:52
If it's different from any filed in https://github.com/JavaMoney/jsr354-ri/issues please file a new one. And don't forget Moneta-BP, if the bug also affects that, we must fix everything for the MR 1 or JSR 354. Only in a follow-up release a new unified RI (e.g. by using Multi-release JARs) will save those extra efforts ;-)

**Comment by stokito** [comment] 2019-02-01 20:44
After debug it tirned out that this is actually a bug inside of JDK (in all versions even in JDK12 preview):

```java
    @Test
    public void formatDecimal() {
        DecimalFormat currencyFormat = (DecimalFormat)DecimalFormat.getCurrencyInstance(GERMANY);
        Currency eur = Currency.getInstance("EUR");
        currencyFormat.setCurrency(eur);
        currencyFormat.applyPattern("#,##0.## ¤");
        String formatted = currencyFormat.format(-42);
        assertEquals(formatted, "-42 €"); //OK

        currencyFormat.applyPattern(" #,##0.## ¤"); // pattern with leading space
        formatted = currencyFormat.format(-42);
        assertEquals(formatted, " -42 €"); //AssertionError: expected [ -42 €] but found [- 42 €]
    }
```

So instead of  ` -42 €` with leading space from pattern it returns  `- 42 €`  with space after minus.
I think we should file and issue to openjdk but even if it will be fixed and backported to JDK8 then anyway in bloody enterprise nobody ever updates their JDK8.
That's why we should think how to fix it.

**Comment by keilw** [comment] 2019-05-16 08:35
@stokito Not sure, what restrictions exist to create an account, but could you maybe raise the bug with the OpenJDK ticket system? @JavaMoney/developers if anyone already works on OpenJDK, maybe he/she could help.

**Comment by stokito** [comment] 2019-05-16 11:35
Well, I can submit the bug to bugs.java.com and *maybe one day* someone from support team will create a ticket on bugs.openjdk jira.
I submitted a bug with ID 9060791 and it waiting for a review.

**Comment by stokito** [comment] 2019-05-17 06:33
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8224093

**Comment by silk-bahamut** [comment] 2019-09-19 09:40
@keilw The bug is still present when applying the preconised solution : using a positive and a negative pattern :
`@Test
  public void test() {
    MonetaryAmountFormat formatter = MonetaryFormats.getAmountFormat(
        AmountFormatQueryBuilder.of(Locale.US)
            .set(CurrencyStyle.CODE)
            .set(AmountFormatParams.PATTERN, "¤ ###0.00;¤ -###0.00")
            .build());
    Assertions.assertThat(formatter.parse("EUR -10.00")).isEqualTo(Money.of(-10, "EUR")); // OK
    Assertions.assertThat(formatter.format(Money.of(-10, "EUR"))).isEqualTo("EUR -10.00"); // KO : EUR- -10.00
  }`

And the test with jdk do work nicely
`  @Test
  void testDecimalFormat() throws Exception {
    DecimalFormatSymbols dfs = DecimalFormatSymbols.getInstance();
    dfs.setDecimalSeparator('.');
    DecimalFormat formatter = new DecimalFormat(" ###0.00; -###0.00", dfs);
    Assertions.assertThat(formatter.parse(" -10.50")).isEqualTo(-10.5d); // OK
    Assertions.assertThat(formatter.format(-10.5d)).isEqualTo(" -10.50"); // OK
  }`

**Comment by keilw** [comment] 2019-09-19 10:26
Well it seems OpenJDK pointed to that lesser used "multi pattern" in https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8224093 because the ticket was closed as not a bug or "won't fix".  I can't say from the top of my head, if `.set(AmountFormatParams.PATTERN, "¤ ###0.00;¤ -###0.00")` is supposed to work right now, @atsticks, @stokito any idea, if that is supported?

**Comment by silk-bahamut** [comment] 2019-09-19 12:51
I'm currently using Oracle JDK

**Comment by keilw** [comment] 2019-09-19 13:35
Could you try OpenJDK because if it only works in the Oracle commercial product, it may not be representative? I hope it works broader because they said it works in the OpenJDK tracker, but better test with multiple runtimes.

**Comment by silk-bahamut** [comment] 2019-09-19 14:02
The results are the same regarding the JDK for both tests

**Comment by atsticks** [comment] 2020-01-07 00:12
The test:

```
@Test
  public void test() {
    MonetaryAmountFormat formatter = MonetaryFormats.getAmountFormat(
        AmountFormatQueryBuilder.of(Locale.US)
            .set(CurrencyStyle.CODE)
            .set(AmountFormatParams.PATTERN, "¤ ###0.00;¤ -###0.00")
            .build());
    Assertions.assertThat(formatter.parse("EUR -10.00")).isEqualTo(Money.of(-10, "EUR")); // OK
    Assertions.assertThat(formatter.format(Money.of(-10, "EUR"))).isEqualTo("EUR -10.00"); // KO : EUR- -10.00
  }
```

actually works with the latest commit. So I tend to close this ticket.

**Closed by atsticks** 2020-01-07 00:12 UTC
Labels: analysis
