### ISSUE TITLE
Some format tests failing

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri#202] opened 2018-06-05 23:34 UTC
While the overall build seems unaffected (ideally none should fail) there are failing tests seen in the latest build.

Failed tests: 
  MonetaryAmountFormatTest.testFormat:48 expected [12,50 CHF] but found [12,50 CHF]
  MonetaryAmountFormatTest.testFormatWithBuilder2:90 expected [12,50 756] but found [12,50 756]
  MonetaryAmountFormatTest.testParse:145 » MonetaryParse Unparseable number: "12...
  MonetaryAmountFormatTest.testPrint:111 expected [12,50 CHF] but found [12,50 CHF]
  MonetaryAmountFormatTest.testWithCustomPattern:172 expected [12.345,23 €] but found [12.345,23 €]

Some of them are extremely weird because the assertion does not make any sense.

**Comment by stokito** [comment] 2019-01-14 10:46
duplicate of #208

**Comment by keilw** [comment] 2019-01-14 13:15
That's why that one has been closed.

**Comment by stokito** [comment] 2019-01-26 21:04
Let's close it as a duplicate of #193 because I fixed this issue with NBSP during a work on that issue

**Comment by stokito** [comment] 2019-01-29 13:33
Fixed, please check and close the tocket

**Closed** 2019-05-17 08:01 UTC
Labels: Priority: Critical, bug, showstopper
