### ISSUE TITLE
MonetaryAmountFormat.format NPE

### ISSUE THREAD

**Issue by cyberluke** [JavaMoney/jsr354-ri#283] opened 2019-02-01 15:09 UTC
```
        CurrencyUnit EOSUnit = CurrencyUnitBuilder
                .of("EOS", "EosCurrencyProvider") // Set currency code and currency provider name
                .setDefaultFractionDigits(4)      // Set default fraction digits
                .build(true);  

        final MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(
                AmountFormatQueryBuilder.of(Locale.US)
                        .set(CurrencyStyle.CODE)
                        .set(AmountFormatParams.PATTERN, "0.00")
                        .build()
        );

        System.out.println(Monetary.isCurrencyAvailable("EOS"));
        System.out.println(format.format(Money.of(0.025, "EOS")));
        System.out.println(format.parse("0.01 EOS"));
```

**Result:**
```
true
16:06:24.026 [http-nio-8337-exec-3] INFO  org.javamoney.moneta.DefaultMonetaryContextFactory - Using custom MathContext: precision=256, roundingMode=HALF_EVEN
0.02
java.lang.NullPointerException
```

**Comment by cyberluke** [comment] 2019-02-01 15:12
If
.set(AmountFormatParams.PATTERN, "0.0000 ¤")
Then format.parse outputs
EOS 0.010000000000000000000000000000000000000000000000000000000000000

So when how the hell can I parse String with currency and output in corrent format 0.0000 ¤ ?

**Comment by stokito** [comment] 2019-02-01 16:11
Hi @cyberluke thank you for reporting and sorry for the problems. Formatting is still not so stable but in next release there should be few fixes of well known bugs.
Can you please try a 1.4-SHANPSHOT version?
To try it you should use those repositories in a POM like https://github.com/JavaMoney/javamoney-examples/blob/master/pom.xml shows.

**Comment by cyberluke** [comment] 2019-02-01 16:20
Duh, killed 2 hours of my contract salary. I can, someday, but not today. I use gradle, will alter it. Thanks.

**Comment by keilw** [comment] 2019-02-01 17:34
For 354 Gradle is out of question. For a follow-up JSR we consider it.

**Comment by cyberluke** [comment] 2019-02-01 18:16
What is 354? Do you know what is Gradle? Do you know you can import any Maven package in Gradle?

**Comment by keilw** [comment] 2019-02-01 18:42
JSR 354, that's the project here ;-) 
https://javamoney.github.io/ri.html shows the recent dependencies, Sites like https://search.maven.org/artifact/org.javamoney/moneta/1.3/pom show you how to import it in Gradle.

**Comment by cyberluke** [comment] 2019-02-01 18:52
I know. Hey man, I know it's Friday :-D ...I wrote: "I use gradle, will alter it". It meant that pom.xml is not a satisfactory to copy/paste, but I can live with it and will alter it. You just transform XML to Groovy. They are not friends, but they are not at war either.

**Comment by stokito** [comment] 2019-02-03 00:08
Ok, so I tested your code and it turned out that you have missed a currency sign `¤` in the pattern so the correct patter is `0.00 ¤`. Without this we don't know where the currency code is located: on start or on end.
If so then the whole pattern is treated as a number only and currency is just ignored.

Thus `format` instance can be used for formatting but not for parsing.
It may be ok to parse only amounts if you can set the currency manually via `amountFormatContext.set(CurrencyUnit.class, EOSUnit)` .

Anyway I refactored that place and improve error message.

**Comment by cyberluke** [comment] 2019-02-03 09:48
Yes, exactly. I sent it without currency symbol, because I got close to my solution. But problem is, when I used it, I got: EOS 0.010000000000000000000000000000000000000000000000000000000000000

No matter what locale I choose. It should be 0.0100 EOS (4 decimal points, currency at the end). No matter if I choose Germany or Japan for locale, stilll bad. Also the problem is, when you use "," or "." for divider. I see "." is only in US locale, but they put the currency in the front. That's why I used custom formatting to solve this issue.

You mention on your website that you support BTC and custom currencies. But I got several headaches just with simple demo and spent 2 hours on it. Then used just String.format, lol.

**Comment by cyberluke** [comment] 2019-02-03 10:09
The reason I had to use format instance for parsing is that I tried Money.parse() before and it had even worse issues :-D Welcome to open-source.

**Comment by stokito** [comment] 2019-02-03 13:20
Well... you incorrectly understood the pattern format. In fact internally JavaMoney delegates parsing to JDK's  [DecimalFormat](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/DecimalFormat.html) and you may see from its JavaDoc in "Special Pattern Characters" section that the dot in pattern is abstract "decimal separator" and will be replaced to comma or a dot depending on the choosed locale.
That's why you got comma only when you set US locale.

But JavaMoney's tutorial or JavaDoc should clearly says about this to avoid such misunderstandings.
As you said "Welcome to open-source" so if you can send us PR with improvement of documentation that will be great: docs created by users is always better to understand.

But the `0.010000000000000000000000000000000000000000000000000000000000000` is definitely a bug that should be fixed. I debugged and this happens because the parsed BigDecimal instance then changed with default scale 64 inside of `MoneyUtils#getBigDecimal` method. I have no idea what was initial intention for this so can't fix it. Interesting that other unit tests didn't captured the error. 

Thank you for your feedback.

**Comment by keilw** [comment] 2019-02-03 14:05
Could you either rephrase this one or create a new ticket for the `0.010000000000000000000000000000000000000000000000000000000000000` and close this one?

**Comment by stokito** [comment] 2019-02-03 15:01
@keilw in my PR #287 was added a test case to the DefaultMonetaryAmountFormatTest which reproduces the bug with to string.
But I don't think it worst to for a separate issue. At least we should improve a documentation\tutorials\javadoc in scope of the issue.

**Comment by cyberluke** [comment] 2019-02-03 15:09
I know about the locale settings. Just telling you.

**Comment by cyberluke** [comment] 2019-02-03 15:19
I ask someone in the company, if they let me help you and it's worth the time or if String.format and string concatenation is ok as it solves our current case. You know about how it works with management in the companies, right?

It is a more broad problem. Current state of most companies is that they want everything fast. No company develop their technologies anymore. They just put open-source libraries together and put a burden & trust on OSS projects and their maintainers. You can see the same situation everywhere, for example MongoDB being raped by corpoRats. This is the age of opensource and stackoverflows :-D. I like programming, I will be glad to help. Just, if you would know how to formulate this the sentence I should write to someone like VP of Software Engineering. We have half implemented scrum for 5 months. So now it's about standups, babysitting and sprints. Last month one colleague got already fired, because even though he is smart, he miscommunicated what he doing on standups.

**Comment by stokito** [comment] 2019-02-17 20:22
You may be interested in #294 which was created partially based on your problem when you tried to use a pattern without a currency sign.

**Comment by atsticks** [comment] 2020-01-07 00:07
Probably fixed with latest commits.

**Closed** 2020-01-07 00:07 UTC
Labels: analysis
