### ISSUE TITLE
Money.toString() and Money.parse(…) not symmetric anymore

### ISSUE THREAD

**Issue by odrotbohm** [JavaMoney/jsr354-ri#357] opened 2021-05-08 20:46 UTC
Similarly to #319, the change made for #307 breaks print/parse symmetry without any kind of formatting involved. Assume you want to serialize (generally, not in a Java serialize way) a `Money` via `toString()` to eventually recreate it via `Money.parse(…)`. Up until version 1.4, the following worked:

```java
MonetaryAmount source = Money.of(1.23456, "EUR");
assertThat(Money.parse(source.toString)).isEqualTo(source);
```

This now fails with "Expected is <EUR 1.23> but was <EUR 1.23>". The reason for this is that as of 1.4 (#307) `toString()` now applies some default formatting, which I think is not only wrong, it's also highly misleading as you can see from the assertion message, as the source value is *not* 1.23, but 1.2345.

**Comment by keilw** [comment] 2021-05-08 21:18
Can you explain why you mentioned `MonetaryAmount.toString()`?
It is an interface and does not declare a `toString()` method, neither `abstract` nor `default`.

**Comment by odrotbohm** [comment] 2021-05-08 21:24
In the production code, I work with a `MonetaryAmount` but effectively it is a `Money` instance. I've updated the summary and description accordingly.

**Comment by keilw** [comment] 2021-05-14 17:50
Also here please be patient until https://issues.sonatype.org/browse/OSSRH-68317 can be resolved by Sonatype because for some totally unknown and strange reason the same Sonatype user which never had problems to sync from Bintray while that was still around suddenly fails to deploy snapshots directly. Hope they can fix that soon, because no other "technical" or personal account I use for other projects and JSRs ever failed, only the "JavaMoney" one.

**Comment by keilw** [comment] 2023-02-12 15:43
All tests in moneta-core pass now, except 4 that are related to config issues (#353), I trust the above mentioned problem is now fixed, otherwise please reopen or create a new one with steps to reproduce.

**Comment by keilw** [comment] 2023-02-14 19:18
There are two parts in this problem:

1. Using `MonetaryAmount amount = Monetary.getDefaultRounding().apply(this);` in all relevant toString() operations, not just `Money`, which in the given example already rounds down the amount to 1.23. The only one or two unit tests taking the rounding down away and formatting `this `instead those for currency code "XXX", e.g. 
2. applying a flexible/customizable scale in the `ToStringMonetaryAmountFormat`.

**Comment by keilw** [comment] 2023-02-14 21:44
Actually the majority of test failures were pretty much the same, so avoiding the round-down plus an adjustment of the scale that also takes the `maxScale  and `fixedScale `combination into consideration works pretty well.

**Comment by keilw** [comment] 2023-04-23 12:32
Did not hear anything by either one, so I assume that is resolved.

**Closed by keilw** 2023-04-23 12:32 UTC
Labels: Priority: High, formatting

**Comment by stefanzilske** [comment] 2024-02-05 11:30
Hey, I just noticed, after upgrading from 1.4.2, that the previously applied default rounding to a fixed scale=2 in toString() is not applied anymore. We heavily rely on this, e.g. whenever we serialize a Money value to JSON. So it's a quite invasive breaking change.

Is there a way to apply this default rounding? I stumbled upon MonetaryConfig, but found no usable documentation on how to best do this in SpringBoot.

**Comment by keilw** [comment] 2024-02-05 17:14
The hardcoded scale for toString() was what had to be fixed here, so adding it back would only be possible as an optional property, Please create an enhancement request here, and we'll see, if we could add something into javamoney.properties to customize it. 
In the meantime you should be able to enforce the scale of your choice by creating your `Money` this way:
```
Money money3 = Money.of(1234567.3, "EUR", MonetaryContextBuilder.of().setMaxScale(2).setFixedScale(true).build());
System.out.println(money2.toString());

```
prints "EUR 1234567.30".

**Comment by keilw** [comment] 2024-02-20 20:17
@stefanzilske I saw #364 had been around for some time, we did not really plan to do this (especially the desire to just print "a" or something) until a much later version, but it seems fair to "hijack" it for your particular requirement and customize both 
`toString()` and `parse()`, e.g. by restricting the scale.

I linked them this way, but it would be nice to mention a few words about the requirement in #364 if you can.

Btw, there are currently no plans to configure Moneta via the SpringBoot `application.properties`. Although the Spring Framework (and thus also Spring Boot) support formatting via JSR 354, the JSR is runtime-agnostic and works with all other Microframeworks just as well.
